version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assignment_resource
    ports:
      - "8000:7755"
    environment:
      - FLASK_APP=core/server.py
    volumes:
      - ./data:/app/data
    command: bash -c "./script.sh"